-- NPS KING database setup for Supabase
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id text primary key default 'main',
  data jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  pran text,
  city text,
  corpus text,
  plan_type text,
  status text not null default 'pending' check (status in ('pending','underprocess','completed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  city text,
  budget text,
  source text,
  keyword text,
  created_at timestamptz not null default now()
);

create index if not exists customers_phone_idx on public.customers(phone);
create index if not exists customers_pran_idx on public.customers(pran);
create index if not exists leads_created_at_idx on public.leads(created_at desc);

alter table public.site_settings enable row level security;
alter table public.customers enable row level security;
alter table public.leads enable row level security;

-- Remove old policies if this script is re-run.
drop policy if exists "authenticated can read settings" on public.site_settings;
drop policy if exists "authenticated can write settings" on public.site_settings;
drop policy if exists "authenticated can read customers" on public.customers;
drop policy if exists "authenticated can write customers" on public.customers;
drop policy if exists "authenticated can read leads" on public.leads;
drop policy if exists "authenticated can update leads" on public.leads;
drop policy if exists "authenticated can delete leads" on public.leads;
drop policy if exists "public can insert leads" on public.leads;
drop policy if exists "public can read settings" on public.site_settings;

create policy "authenticated can read settings"
on public.site_settings for select to authenticated using (true);
create policy "authenticated can write settings"
on public.site_settings for all to authenticated using (true) with check (true);

create policy "authenticated can read customers"
on public.customers for select to authenticated using (true);
create policy "authenticated can write customers"
on public.customers for all to authenticated using (true) with check (true);

create policy "authenticated can read leads"
on public.leads for select to authenticated using (true);
create policy "authenticated can update leads"
on public.leads for update to authenticated using (true) with check (true);
create policy "authenticated can delete leads"
on public.leads for delete to authenticated using (true);
create policy "public can insert leads"
on public.leads for insert to anon, authenticated with check (true);

-- Public visitors need the business/site settings to render the landing page.
-- They cannot write settings because the write policies remain authenticated-only.
create policy "public can read settings"
on public.site_settings for select to anon, authenticated using (id = 'main');

-- Public application-status lookup. It returns only the minimum fields needed by the website.
create or replace function public.check_application(search_value text)
returns table(name text, pran text, status text)
language sql
security definer
set search_path = public
as $$
  select c.name, c.pran, c.status
  from public.customers c
  where nullif(regexp_replace(coalesce(search_value,''), '[^0-9A-Za-z]', '', 'g'), '') is not null
    and (regexp_replace(coalesce(c.phone,''), '[^0-9]', '', 'g') = regexp_replace(search_value, '[^0-9]', '', 'g')
      or lower(regexp_replace(coalesce(c.pran,''), '[^0-9A-Za-z]', '', 'g')) = lower(regexp_replace(search_value, '[^0-9A-Za-z]', '', 'g')))
  limit 1;
$$;

grant execute on function public.check_application(text) to anon, authenticated;

-- Optional seed: insert the public site settings once after replacing the JSON below with your preferred values.
-- The website will also create settings automatically on first admin save.
